### ISSUE TITLE
error while running the code

### ISSUE THREAD

**Issue by shabidkhan** [yogendra3236/Facebook-Scraper#1]
Traceback (most recent call last):
  File "/home/kapil/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver': 'chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fb.py", line 15, in <module>
    driver = webdriver.Chrome(chrome_options=driver)
  File "/home/kapil/.local/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/kapil/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by yogendra3236** [comment]
@shabidkhan you've not initialized the correct path of chromedriver. Please download and place it properly to execute the code. This is not the issue with the code. Please ask these questions separately on stackoverflow.com.
Closing now! Thanks!
